# Generated by Django 2.0.10 on 2019-02-18 20:40

from django.conf import settings
from django.db import migrations, models
import repo_scanner.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('filepath', models.CharField(max_length=300)),
                ('scandate', models.DateTimeField(auto_now=True)),
                ('filecreationdate', models.DateTimeField(blank=True, null=True)),
                ('bitrate', models.IntegerField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('samplerate', models.IntegerField(blank=True, null=True)),
                ('lufs', models.FloatField(blank=True, null=True)),
                ('channels', models.IntegerField(blank=True, null=True)),
                ('crc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_target_root', models.CharField(default='/audio_repo', max_length=300)),
                ('scan_slug', models.CharField(default='2019-02-18 20:40', max_length=100)),
                ('scan_desc', models.CharField(default='Scan Started @ 2019-02-18 20:40', max_length=500)),
                ('scan_datetime', models.DateTimeField(default=repo_scanner.models.default_scan_start_time)),
                ('created_by', models.ForeignKey(on_delete='cascade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
