# Generated by Django 2.0.10 on 2019-02-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo_scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioasset',
            name='scandate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
