# Generated by Django 2.0.10 on 2019-02-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo_scanner', '0002_audioasset_scandate'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioasset',
            name='bitrate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='audioasset',
            name='channels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audioasset',
            name='crc',
            field=models.CharField(default='xxxxxxxx', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audioasset',
            name='length',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='audioasset',
            name='lufs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='audioasset',
            name='samplerate',
            field=models.IntegerField(default=0),
        ),
    ]
