# Generated by Django 2.0.10 on 2019-02-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo_scanner', '0003_auto_20190203_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioasset',
            name='bitrate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='audioasset',
            name='channels',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='audioasset',
            name='crc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audioasset',
            name='length',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='audioasset',
            name='lufs',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='audioasset',
            name='samplerate',
            field=models.IntegerField(null=True),
        ),
    ]
