# Generated by Django 2.0.10 on 2019-02-07 22:45

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('repo_scanner', '0005_scantask'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantask',
            name='file_obj',
            field=models.FileField(default=django.utils.timezone.now, storage=django.core.files.storage.FileSystemStorage(location='/'), upload_to=''),
            preserve_default=False,
        ),
    ]
