# Generated by Django 2.0.10 on 2019-02-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo_scanner', '0006_scantask_file_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantask',
            name='file_obj',
            field=models.URLField(),
        ),
    ]
