# Generated by Django 2.0.10 on 2019-02-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo_scanner', '0008_auto_20190207_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantask',
            name='file_obj',
            field=models.FilePathField(max_length=300, path='/'),
        ),
    ]
