# Generated by Django 2.0.10 on 2019-02-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo_scanner', '0012_auto_20190211_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scantask',
            name='file_obj',
        ),
        migrations.AlterField(
            model_name='scantask',
            name='scan_desc',
            field=models.CharField(default='Scan Started @ 2019-02-11 20:10', max_length=500),
        ),
        migrations.AlterField(
            model_name='scantask',
            name='scan_root',
            field=models.CharField(default='/audio_repo', max_length=300),
        ),
        migrations.AlterField(
            model_name='scantask',
            name='scan_slug',
            field=models.CharField(default='2019-02-11 20:10', max_length=100),
        ),
    ]
