# Generated by Django 2.0.10 on 2019-02-11 21:56

from django.db import migrations, models
import repo_scanner.models


class Migration(migrations.Migration):

    dependencies = [
        ('repo_scanner', '0013_auto_20190211_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scantask',
            old_name='scan_root',
            new_name='scan_target_root',
        ),
        migrations.RemoveField(
            model_name='scantask',
            name='active',
        ),
        migrations.RemoveField(
            model_name='scantask',
            name='recurrence',
        ),
        migrations.AddField(
            model_name='scantask',
            name='scan_datetime',
            field=models.DateTimeField(default=repo_scanner.models.default_scan_start_time),
        ),
        migrations.AlterField(
            model_name='scantask',
            name='scan_desc',
            field=models.CharField(default='Scan Started @ 2019-02-11 21:56', max_length=500),
        ),
        migrations.AlterField(
            model_name='scantask',
            name='scan_slug',
            field=models.CharField(default='2019-02-11 21:56', max_length=100),
        ),
    ]
